# Generated by Django 4.2.7 on 2024-12-14 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='modified',
            new_name='updated_at',
        ),
    ]
