# Generated by Django 4.2.7 on 2024-12-14 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_created_employee_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre del banco', max_length=100)),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'ordering': ['name'],
            },
        ),
        migrations.RenameModel(
            old_name='EmployeeStatus',
            new_name='Status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='bank',
            field=models.ForeignKey(default=None, help_text='Banco', on_delete=django.db.models.deletion.PROTECT, to='employees.bank'),
            preserve_default=False,
        ),
    ]
