# Generated by Django 4.2.7 on 2024-12-16 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_rename_weklyloan_weeklyloan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del nivel educación')),
            ],
            options={
                'verbose_name': 'Educación',
                'verbose_name_plural': 'Educaciones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del idioma')),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['name'], 'verbose_name': 'Banco', 'verbose_name_plural': 'Bancos'},
        ),
        migrations.AlterModelOptions(
            name='colony',
            options={'ordering': ['name'], 'verbose_name': 'Colonia', 'verbose_name_plural': 'Colonias'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='maritalstatus',
            options={'ordering': ['name'], 'verbose_name': 'Estado Civil', 'verbose_name_plural': 'Estados Civiles'},
        ),
        migrations.AlterModelOptions(
            name='municipality',
            options={'ordering': ['name'], 'verbose_name': 'Municipio', 'verbose_name_plural': 'Municipios'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['name'], 'verbose_name': 'Estatus de empleado', 'verbose_name_plural': 'Estatus de empleados'},
        ),
        migrations.AlterModelOptions(
            name='weeklyloan',
            options={'verbose_name': 'Préstamo semanal', 'verbose_name_plural': 'Préstamos semanales'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='born_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='address_number',
            field=models.CharField(blank=True, help_text='Número de la casa o departamento', max_length=10, null=True, verbose_name='Número de residencia'),
        ),
        migrations.AddField(
            model_name='employee',
            name='address_street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Calle de residencia'),
        ),
        migrations.AddField(
            model_name='employee',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono de emergencia'),
        ),
        migrations.AddField(
            model_name='employee',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estatura en metros', max_digits=3, null=True, verbose_name='Estatura'),
        ),
        migrations.AddField(
            model_name='employee',
            name='ine',
            field=models.CharField(blank=True, help_text='Número de credencial de Instituto Nacional Electoral', max_length=13, null=True, verbose_name='INE'),
        ),
        migrations.AddField(
            model_name='employee',
            name='knowledge',
            field=models.TextField(blank=True, help_text='Conocimientos y experiencia del empleado', null=True, verbose_name='Conocimientos'),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido paterno'),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido materno'),
        ),
        migrations.AddField(
            model_name='employee',
            name='municipality_birth',
            field=models.ForeignKey(blank=True, help_text='Estado y municipio de nacimiento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='municipality_birth', to='employees.municipality', verbose_name='Lugar de nacimiento'),
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.TextField(blank=True, help_text='Habilidades y destrezas del empleado', null=True, verbose_name='Habilidades'),
        ),
        migrations.AddField(
            model_name='employee',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kilogramos', max_digits=5, null=True, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre del banco'),
        ),
        migrations.AlterField(
            model_name='colony',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre de la colonia'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='administrative_comments',
            field=models.TextField(blank=True, help_text='Detalles de las infracciones administrativas', null=True, verbose_name='Comentarios administrativos'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='administrative_violations',
            field=models.IntegerField(blank=True, help_text='Número de infracciones administrativas hasta la fecha', null=True, verbose_name='Infracciones administrativas'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='anti_doping_results',
            field=models.TextField(blank=True, null=True, verbose_name='Resultados de antidoping'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo de préstamos'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank',
            field=models.ForeignKey(blank=True, help_text='Banco donde se deposita el salario', null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.bank', verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='card_number',
            field=models.CharField(blank=True, help_text='Número de tarjeta de débito o nómina', max_length=16, null=True, verbose_name='Número de tarjeta'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='colony',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.colony', verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='curp',
            field=models.CharField(blank=True, help_text='Clave Única de Registro de Población', max_length=18, null=True, verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Slario diario'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='imss',
            field=models.CharField(blank=True, help_text='Instituto Mexicano del Seguro Social', max_length=11, null=True, verbose_name='IMSS'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='infonavit',
            field=models.CharField(blank=True, help_text='Instituto del Fondo Nacional de la Vivienda para los Trabajadores', max_length=11, null=True, verbose_name='INFONAVIT'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.maritalstatus', verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='municipality',
            field=models.ForeignKey(blank=True, help_text='Estado y municipio de residencia', null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.municipality', verbose_name='Lugar de residencia'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='postal_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rfc',
            field=models.CharField(blank=True, help_text='Registro Federal de Contribuyentes', max_length=13, null=True, verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.status', verbose_name='Estatus de empleado'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status_history',
            field=models.TextField(blank=True, help_text='Historial de estatus (activo, inactivo, baja, etc). Autollenado', null=True, verbose_name='Historial de estatus'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='uniform_date',
            field=models.DateField(blank=True, help_text='Fecha de entrega de uniforme', null=True, verbose_name='Fecha de uniforme'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificación'),
        ),
        migrations.AlterField(
            model_name='maritalstatus',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre del estado civil'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre del municipio'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre del estado'),
        ),
        migrations.AlterField(
            model_name='weeklyloan',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Monto pedido (-) o pagado (+)', max_digits=10, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='weeklyloan',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='weeklyloan',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Empleado'),
        ),
        migrations.CreateModel(
            name='Ref',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=10, verbose_name='Teléfono de referencia')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de referencia')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Empleado')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.education', verbose_name='Nivel de educación'),
        ),
        migrations.AddField(
            model_name='employee',
            name='languages',
            field=models.ManyToManyField(blank=True, null=True, to='employees.language', verbose_name='Idiomas'),
        ),
    ]
