# Generated by Django 4.2.7 on 2024-12-16 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_education_language_alter_bank_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address_number',
            field=models.CharField(default=0, help_text='Número de la casa o departamento', max_length=10, verbose_name='Número de residencia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='address_street',
            field=models.CharField(default='', max_length=100, verbose_name='Calle de residencia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='administrative_violations',
            field=models.IntegerField(default=0, help_text='Número de infracciones administrativas hasta la fecha', verbose_name='Infracciones administrativas'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='anti_doping_results',
            field=models.TextField(default='Sin resultados de antidoping', verbose_name='Resultados de antidoping'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo de préstamos'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birthdate',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='colony',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.colony', verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='curp',
            field=models.CharField(help_text='Clave Única de Registro de Población', max_length=18, verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Slario diario'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.education', verbose_name='Nivel de educación'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_phone',
            field=models.CharField(max_length=10, verbose_name='Teléfono de emergencia'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ine',
            field=models.CharField(help_text='Número de credencial de Instituto Nacional Electoral', max_length=13, verbose_name='INE'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='knowledge',
            field=models.TextField(help_text='Conocimientos y experiencia del empleado', verbose_name='Conocimientos'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='languages',
            field=models.ManyToManyField(to='employees.language', verbose_name='Idiomas'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name_1',
            field=models.CharField(max_length=100, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='municipality',
            field=models.ForeignKey(help_text='Estado y municipio de residencia', on_delete=django.db.models.deletion.PROTECT, to='employees.municipality', verbose_name='Lugar de residencia'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='municipality_birth',
            field=models.ForeignKey(help_text='Estado y municipio de nacimiento', on_delete=django.db.models.deletion.PROTECT, related_name='municipality_birth', to='employees.municipality', verbose_name='Lugar de nacimiento'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=10, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='postal_code',
            field=models.CharField(max_length=5, verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='skills',
            field=models.TextField(help_text='Habilidades y destrezas del empleado', verbose_name='Habilidades'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='employees.status', verbose_name='Estatus de empleado'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación'),
        ),
    ]
