# Generated by Django 4.2.7 on 2024-12-16 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_address_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de relación')),
            ],
            options={
                'verbose_name': 'Parentesco',
                'verbose_name_plural': 'Parentescos',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['id'], 'verbose_name': 'Educación', 'verbose_name_plural': 'Educaciones'},
        ),
        migrations.AlterModelOptions(
            name='ref',
            options={'verbose_name': 'Referencia', 'verbose_name_plural': 'Referencias'},
        ),
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de familiar')),
                ('last_name_1', models.CharField(max_length=100, verbose_name='Apellido paterno')),
                ('last_name_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido materno')),
                ('relationship', models.CharField(max_length=100, verbose_name='Parentesco')),
                ('phone', models.CharField(max_length=10, verbose_name='Teléfono de familiar')),
                ('age', models.IntegerField(verbose_name='Edad de familiar')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Familiar',
                'verbose_name_plural': 'Familiares',
            },
        ),
    ]
