# Generated by Django 4.2.7 on 2024-12-16 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_relationship_alter_education_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relative',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.relationship', verbose_name='Parentesco'),
        ),
    ]
