# Generated by Django 4.2.7 on 2024-12-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_relative_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status_history',
            field=models.TextField(default='', help_text='Historial de estatus (activo, inactivo, baja, etc). Autollenado', verbose_name='Historial de estatus'),
        ),
    ]
