# Generated by Django 4.2.7 on 2024-12-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_alter_employee_status_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status_change_details',
            field=models.TextField(blank=True, help_text='Detalles del cambio de estatus', null=True, verbose_name='Detalles de cambio de estatus'),
        ),
    ]
