# Generated by Django 4.2.7 on 2024-12-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employee_status_change_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, help_text='Fotografía del empleado (tamaño recomendado: 300x300px)', null=True, upload_to='employees/photos/', verbose_name='Foto'),
        ),
    ]
