# Generated by Django 4.2.7 on 2024-12-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_rename_weeklyloan_loan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name': 'Préstamo', 'verbose_name_plural': 'Préstamos'},
        ),
        migrations.AddField(
            model_name='loan',
            name='details',
            field=models.TextField(blank=True, help_text='Detalles del préstamo o pago', null=True, verbose_name='Detalles'),
        ),
    ]
