# Generated by Django 4.2.7 on 2024-12-18 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_alter_loan_options_loan_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro'),
        ),
    ]
