# Generated by Django 4.2.7 on 2024-12-18 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_loan_updated_at_alter_loan_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Colony',
            new_name='Neighborhood',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='colony',
            new_name='neighborhood',
        ),
        migrations.AddField(
            model_name='employee',
            name='service',
            field=models.TextField(default='Sin servicio', help_text='Servicio que asignado el empleado', verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sueldo diario'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificación'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de prestamo o pago'),
        ),
    ]
