# Generated by Django 4.2.7 on 2024-12-20 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_alter_employee_height_alter_employee_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='service',
        ),
    ]
