# Generated by Django 4.2.7 on 2025-02-03 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_remove_employee_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='daily_rate',
            new_name='weekly_rate',
        ),
    ]
