# Generated by Django 4.2.7 on 2025-02-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_rename_daily_rate_employee_weekly_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='weekly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario semanal'),
        ),
    ]
