# Generated by Django 4.2.7 on 2025-02-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_alter_employee_weekly_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='card_number',
            field=models.CharField(blank=True, help_text='Número de tarjeta de débito o nómina', max_length=16, null=True, unique=True, verbose_name='Número de tarjeta'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='curp',
            field=models.CharField(help_text='Clave Única de Registro de Población', max_length=18, unique=True, verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='imss',
            field=models.CharField(blank=True, help_text='Instituto Mexicano del Seguro Social', max_length=11, null=True, unique=True, verbose_name='IMSS'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ine',
            field=models.CharField(help_text='Número de credencial de Instituto Nacional Electoral', max_length=13, unique=True, verbose_name='INE'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='infonavit',
            field=models.CharField(blank=True, help_text='Instituto del Fondo Nacional de la Vivienda para los Trabajadores', max_length=11, null=True, unique=True, verbose_name='INFONAVIT'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=10, unique=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rfc',
            field=models.CharField(blank=True, help_text='Registro Federal de Contribuyentes', max_length=13, null=True, unique=True, verbose_name='RFC'),
        ),
    ]
