# Generated by Django 4.2.7 on 2025-02-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_alter_employee_card_number_alter_employee_curp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='balance',
            field=models.FloatField(default=0, verbose_name='Saldo de préstamos'),
        ),
    ]
