# Generated by Django 4.2.7 on 2025-07-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0021_alter_employee_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="code",
            field=models.CharField(
                default=12, editable=False, max_length=6, unique=True
            ),
            preserve_default=False,
        ),
    ]
