# Generated by Django 4.2.7 on 2025-07-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0022_employee_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="municipality_birth",
            field=models.CharField(max_length=100, verbose_name="Lugar de nacimiento"),
        ),
    ]
