# Generated by Django 4.2.7 on 2025-07-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0023_alter_employee_municipality_birth"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Nombre del departamento"
                    ),
                ),
            ],
            options={
                "verbose_name": "Departamento",
                "verbose_name_plural": "Departamentos",
                "ordering": ["name"],
            },
        ),
    ]
