# Generated by Django 4.2.7 on 2025-07-16 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0024_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="employees.department",
                verbose_name="Departamento",
            ),
            preserve_default=False,
        ),
    ]
