# Generated by Django 4.2.7 on 2025-07-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0025_employee_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="is_eventual",
            field=models.BooleanField(default=False, verbose_name="Es eventual"),
        ),
    ]
