# Generated by Django 4.2.7 on 2025-07-17 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0026_employee_is_eventual"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="administrative_violations",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Número de infracciones administrativas hasta la fecha",
                null=True,
                verbose_name="Infracciones administrativas",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="anti_doping_results",
            field=models.TextField(
                blank=True,
                default="Sin resultados de antidoping",
                null=True,
                verbose_name="Resultados de antidoping",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="balance",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="Saldo de préstamos"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="employees.department",
                verbose_name="Departamento",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="education",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="employees.education",
                verbose_name="Nivel de educación",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emergency_phone",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Teléfono de emergencia",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Estatura en metros",
                max_digits=3,
                null=True,
                verbose_name="Estatura",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="knowledge",
            field=models.TextField(
                blank=True,
                help_text="Conocimientos y experiencia del empleado",
                null=True,
                verbose_name="Conocimientos",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="languages",
            field=models.ManyToManyField(
                blank=True, null=True, to="employees.language", verbose_name="Idiomas"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="marital_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="employees.maritalstatus",
                verbose_name="Estado civil",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="municipality_birth",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Lugar de nacimiento",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Teléfono",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="skills",
            field=models.TextField(
                blank=True,
                help_text="Habilidades y destrezas del empleado",
                null=True,
                verbose_name="Habilidades",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="status",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="employees.status",
                verbose_name="Estatus de empleado",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="status_history",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Historial de estatus (activo, inactivo, baja, etc). Autollenado",
                null=True,
                verbose_name="Historial de estatus",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="weekly_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Salario semanal",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Peso en kilogramos",
                max_digits=5,
                null=True,
                verbose_name="Peso",
            ),
        ),
    ]
