# Generated by Django 4.2.7 on 2025-07-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0027_alter_employee_administrative_violations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="qr_image",
            field=models.ImageField(
                default=1, upload_to="employees/qr_images/", verbose_name="Imagen QR"
            ),
            preserve_default=False,
        ),
    ]
