# Generated by Django 4.2.7 on 2025-07-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0028_employee_qr_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="qr_image",
            field=models.ImageField(
                editable=False,
                upload_to="employees/qr_images/",
                verbose_name="Imagen QR",
            ),
        ),
    ]
