# Generated by Django 4.2.7 on 2025-07-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0029_alter_employee_qr_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="code",
            field=models.CharField(
                editable=False,
                max_length=6,
                unique=True,
                verbose_name="Código de empleado",
            ),
        ),
    ]
