# Generated by Django 4.2.7 on 2025-07-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0031_alter_employee_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="qr_image",
            field=models.ImageField(
                upload_to="employees/qr_images/", verbose_name="Imagen QR"
            ),
        ),
    ]
