# Generated by Django 4.2.7 on 2025-07-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0032_alter_employee_qr_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="code",
            field=models.CharField(
                max_length=6, unique=True, verbose_name="Código de empleado"
            ),
        ),
    ]
