# Generated by Django 4.2.7 on 2025-07-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0033_alter_employee_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="languages",
            field=models.ManyToManyField(
                to="employees.language", verbose_name="Idiomas"
            ),
        ),
    ]
