# Generated by Django 4.2.7 on 2024-12-20 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0017_remove_employee_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100, verbose_name='Nombre de la empresa')),
                ('responsible_name', models.CharField(max_length=100, verbose_name='Nombre del responsable')),
                ('responsible_phone', models.CharField(max_length=15, verbose_name='Teléfono del responsable')),
                ('effective_date', models.DateField(verbose_name='Fecha de vigencia')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario sugerido')),
                ('extra_hour_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por hora extra sugerido')),
                ('bonuses', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bonificaciones sugeridas')),
                ('profile_requirements', models.TextField(verbose_name='Requisitos de perfil')),
                ('docs_requirements', models.TextField(verbose_name='Documentos requeridos')),
                ('uniforms', models.TextField(verbose_name='Uniformes')),
                ('safety_equipment', models.TextField(verbose_name='Equipo de seguridad')),
            ],
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('start_time', models.TimeField(verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de fin')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('location', models.TextField(verbose_name='Ubicación')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.agreement', verbose_name='Acuerdo')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Empleado')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.schedules', verbose_name='Horario')),
            ],
        ),
    ]
