# Generated by Django 4.2.7 on 2024-12-20 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_agreement_options_alter_schedules_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreement',
            options={'verbose_name': 'Acuerdo', 'verbose_name_plural': 'Acuerdos'},
        ),
    ]
