# Generated by Django 4.2.7 on 2024-12-20 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_agreement_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreement',
            old_name='created_at',
            new_name='start_date',
        ),
    ]
