# Generated by Django 4.2.7 on 2024-12-20 01:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_rename_created_at_agreement_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del acuerdo'),
        ),
    ]
