# Generated by Django 4.2.7 on 2024-12-20 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_agreement_bonuses_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedules',
            new_name='Schedule',
        ),
    ]
