# Generated by Django 4.2.7 on 2024-12-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_rename_schedules_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='bonuses',
            field=models.TextField(blank=True, null=True, verbose_name='Bonificaciones sugeridas'),
        ),
    ]
