# Generated by Django 4.2.7 on 2024-12-20 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_agreement_bonuses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreement',
            options={'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
    ]
