# Generated by Django 4.2.7 on 2024-12-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_agreement_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='location',
            field=models.CharField(max_length=150, verbose_name='Ubicación'),
        ),
    ]
