# Generated by Django 4.2.7 on 2025-02-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_service_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='hours',
            field=models.IntegerField(default=1, verbose_name='Horas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='weekly_attendances',
            field=models.IntegerField(default=1, verbose_name='Asistencias semanales'),
            preserve_default=False,
        ),
    ]
