# Generated by Django 4.2.7 on 2025-01-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='uuid',
            field=models.UUIDField(help_text='Clave única para el artículo', primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='itemloan',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Cantidad de préstamo'),
        ),
        migrations.AlterField(
            model_name='itemtransaction',
            name='quantity',
            field=models.PositiveIntegerField(help_text='(+) Entrada, (-) Salida', verbose_name='Cantidad de transacción'),
        ),
    ]
