# Generated by Django 4.2.7 on 2025-01-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_item_uuid_alter_itemloan_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='uuid',
            field=models.CharField(help_text='Clave única para el artículo', max_length=36, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
    ]
