# Generated by Django 4.2.7 on 2025-01-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_item_stock_alter_itemloan_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad en inventario'),
        ),
    ]
