# Generated by Django 4.2.7 on 2025-01-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_item_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Detalles'),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.PositiveIntegerField(default=1, help_text='No editable después de la creación (añadir transacciones)', verbose_name='Cantidad en inventario'),
        ),
        migrations.AlterField(
            model_name='item',
            name='uuid',
            field=models.CharField(help_text='Clave única (no editable después de la creación)', max_length=36, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='itemtransaction',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Detalles'),
        ),
    ]
