# Generated by Django 4.2.7 on 2025-01-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_item_details_alter_item_stock_alter_item_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemloan',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Detalles'),
        ),
    ]
