# Generated by Django 4.2.7 on 2024-12-24 19:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0010_alter_service_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('attendance', models.BooleanField(verbose_name='Asistencia')),
                ('extra_paid_hours', models.IntegerField(verbose_name='Horas extras pagadas')),
                ('extra_unpaid_hours', models.IntegerField(verbose_name='Horas extras no pagadas')),
                ('notes', models.TextField(verbose_name='Notas')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Servicio')),
            ],
        ),
    ]
