# Generated by Django 4.2.7 on 2024-12-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistance',
            options={'verbose_name': 'Asistencia diaria', 'verbose_name_plural': 'Asistencias diarias'},
        ),
        migrations.AlterField(
            model_name='assistance',
            name='extra_paid_hours',
            field=models.IntegerField(default=0, verbose_name='Horas extras pagadas'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='extra_unpaid_hours',
            field=models.IntegerField(default=0, verbose_name='Horas extras no pagadas'),
        ),
    ]
