# Generated by Django 4.2.7 on 2024-12-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0002_alter_assistance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='notes',
            field=models.TextField(default='', verbose_name='Notas'),
        ),
    ]
