# Generated by Django 4.2.7 on 2024-12-24 20:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_service_location'),
        ('assistance', '0003_alter_assistance_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyAssistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(default=52, verbose_name='Número de semana')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(default=datetime.datetime(2024, 12, 30, 20, 21, 41, 721120, tzinfo=datetime.timezone.utc), verbose_name='Fecha de fin')),
                ('monday', models.BooleanField(default=False, verbose_name='Lunes')),
                ('thuesday', models.BooleanField(default=False, verbose_name='Martes')),
                ('wednesday', models.BooleanField(default=False, verbose_name='Miércoles')),
                ('thursday', models.BooleanField(default=False, verbose_name='Jueves')),
                ('friday', models.BooleanField(default=False, verbose_name='Viernes')),
                ('saturday', models.BooleanField(default=False, verbose_name='Sábado')),
                ('sunday', models.BooleanField(default=False, verbose_name='Domingo')),
                ('total_extra_paid_hours', models.IntegerField(default=0, verbose_name='Total de horas extras pagadas')),
                ('total_extra_unpaid_hours', models.IntegerField(default=0, verbose_name='Total de horas extras no pagadas')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Asistencia semanal',
                'verbose_name_plural': 'Asistencias semanales',
            },
        ),
    ]
