# Generated by Django 4.2.7 on 2024-12-24 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0004_weeklyassistance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyassistance',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 30, 20, 30, 38, 776764, tzinfo=datetime.timezone.utc), verbose_name='Fecha de fin'),
        ),
    ]
