# Generated by Django 4.2.7 on 2024-12-24 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0005_alter_weeklyassistance_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklyassistance',
            old_name='thuesday',
            new_name='tuesday',
        ),
        migrations.AlterField(
            model_name='weeklyassistance',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 30, 20, 34, 45, 31549, tzinfo=datetime.timezone.utc), verbose_name='Fecha de fin'),
        ),
    ]
