# Generated by Django 4.2.7 on 2024-12-24 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0006_rename_thuesday_weeklyassistance_tuesday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyassistance',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 30, 20, 35, 19, 839278, tzinfo=datetime.timezone.utc), verbose_name='Fecha de fin'),
        ),
    ]
