# Generated by Django 4.2.7 on 2024-12-24 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0007_alter_weeklyassistance_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyassistance',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 30, 20, 43, 3, 159384, tzinfo=datetime.timezone.utc), verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='weeklyassistance',
            name='total_extra_paid_hours',
            field=models.IntegerField(default=0, verbose_name='Horas extras pagadas'),
        ),
        migrations.AlterField(
            model_name='weeklyassistance',
            name='total_extra_unpaid_hours',
            field=models.IntegerField(default=0, verbose_name='Horas extras no pagadas'),
        ),
    ]
