# Generated by Django 4.2.7 on 2024-12-24 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0008_alter_weeklyassistance_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyassistance',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 30, 21, 22, 31, 934971, tzinfo=datetime.timezone.utc), verbose_name='Fecha de fin'),
        ),
    ]
