# Generated by Django 4.2.7 on 2024-12-24 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0009_alter_weeklyassistance_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyassistance',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 30, 22, 17, 50, 517812, tzinfo=datetime.timezone.utc), verbose_name='Fecha de fin'),
        ),
    ]
