# Generated by Django 4.2.7 on 2024-12-24 23:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0010_alter_weeklyassistance_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistance',
            name='weekly_assistance',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='assistance.weeklyassistance', verbose_name='Asistencia semanal'),
        ),
        migrations.AlterField(
            model_name='weeklyassistance',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 30, 23, 0, 1, 87827, tzinfo=datetime.timezone.utc), verbose_name='Fecha de fin'),
        ),
    ]
