# Generated by Django 4.2.7 on 2024-12-24 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0011_assistance_weekly_assistance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyassistance',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 30, 23, 1, 12, 553027, tzinfo=datetime.timezone.utc), verbose_name='Fecha de fin'),
        ),
    ]
