# Generated by Django 4.2.7 on 2024-12-24 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0012_alter_weeklyassistance_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='weeklyassistance',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 30, 23, 40, 3, 959112, tzinfo=datetime.timezone.utc), verbose_name='Fecha de fin'),
        ),
    ]
