# Generated by Django 4.2.7 on 2024-12-25 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0014_alter_assistance_weekly_assistance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyassistance',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 31, 0, 2, 3, 191351, tzinfo=datetime.timezone.utc), verbose_name='Fecha de fin'),
        ),
    ]
