# Generated by Django 4.2.7 on 2024-12-25 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0015_alter_weeklyassistance_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='attendance',
            field=models.BooleanField(default=False, verbose_name='Asistencia'),
        ),
        migrations.AlterField(
            model_name='weeklyassistance',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 31, 0, 4, 58, 589469, tzinfo=datetime.timezone.utc), verbose_name='Fecha de fin'),
        ),
    ]
