# Generated by Django 4.2.7 on 2024-12-25 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0016_alter_assistance_attendance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistance',
            name='service',
        ),
        migrations.AlterField(
            model_name='weeklyassistance',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 31, 22, 10, 18, 302307, tzinfo=datetime.timezone.utc), verbose_name='Fecha de fin'),
        ),
    ]
