# Generated by Django 4.2.7 on 2025-01-09 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0017_remove_assistance_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyassistance',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='weeklyassistance',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 15, 20, 43, 43, 785923, tzinfo=datetime.timezone.utc), verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='weeklyassistance',
            name='week_number',
            field=models.IntegerField(default=2, verbose_name='Número de semana'),
        ),
    ]
