# Generated by Django 4.2.7 on 2025-01-21 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0020_alter_weeklyassistance_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyassistance',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 27, 17, 15, 11, 573136, tzinfo=datetime.timezone.utc), verbose_name='Fecha de fin'),
        ),
    ]
