# Generated by Django 4.2.7 on 2025-01-21 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0028_alter_weeklyassistance_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyassistance',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 27, 20, 27, 18, 957839, tzinfo=datetime.timezone.utc), verbose_name='Fecha de fin'),
        ),
    ]
