# Generated by Django 4.2.7 on 2025-02-03 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0029_alter_weeklyassistance_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyassistance',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 9, 15, 51, 11, 811896, tzinfo=datetime.timezone.utc), verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='weeklyassistance',
            name='week_number',
            field=models.IntegerField(default=5, verbose_name='Número de semana'),
        ),
    ]
