# Generated by Django 4.2.7 on 2025-02-03 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0030_alter_weeklyassistance_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyassistance',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 9, 15, 52, 52, 255167, tzinfo=datetime.timezone.utc), verbose_name='Fecha de fin'),
        ),
    ]
