# Generated by Django 4.2.7 on 2025-02-03 17:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0037_alter_weeklyassistance_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraPaymentCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría de pago extra',
                'verbose_name_plural': 'Categorías de pago extra',
            },
        ),
        migrations.AlterField(
            model_name='weeklyassistance',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 9, 17, 27, 14, 980794, tzinfo=datetime.timezone.utc), verbose_name='Fecha de fin'),
        ),
        migrations.CreateModel(
            name='ExtraPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de actualización')),
                ('assistance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistance.assistance', verbose_name='Asistencia')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistance.extrapaymentcategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Pago extra',
                'verbose_name_plural': 'Pagos extra',
            },
        ),
    ]
