# Generated by Django 4.2.7 on 2025-02-03 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0038_extrapaymentcategory_alter_weeklyassistance_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extrapayment',
            options={'verbose_name': 'Extra', 'verbose_name_plural': 'Extras'},
        ),
        migrations.AlterModelOptions(
            name='extrapaymentcategory',
            options={'verbose_name': 'Categoría de extra', 'verbose_name_plural': 'Categorías de extras'},
        ),
        migrations.AlterField(
            model_name='weeklyassistance',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 9, 17, 28, 5, 662052, tzinfo=datetime.timezone.utc), verbose_name='Fecha de fin'),
        ),
    ]
