# Generated by Django 4.2.7 on 2025-02-03 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0039_alter_extrapayment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='extra_paid_hours',
            field=models.IntegerField(default=0, verbose_name='Hrs extras pagadas'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='extra_unpaid_hours',
            field=models.IntegerField(default=0, verbose_name='Hrs no pagadas'),
        ),
        migrations.AlterField(
            model_name='weeklyassistance',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 9, 20, 54, 49, 80509, tzinfo=datetime.timezone.utc), verbose_name='Fecha de fin'),
        ),
    ]
