# Generated by Django 4.2.7 on 2025-02-03 20:56

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0040_alter_assistance_extra_paid_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='assistance',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='extrapayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='extrapayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='weeklyassistance',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 9, 20, 56, 35, 9265, tzinfo=datetime.timezone.utc), verbose_name='Fecha de fin'),
        ),
    ]
