# Generated by Django 4.2.7 on 2025-02-04 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0050_alter_weeklyassistance_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrapayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='weeklyassistance',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 10, 15, 41, 33, 584831, tzinfo=datetime.timezone.utc), verbose_name='Fecha de fin'),
        ),
    ]
