# Generated by Django 4.2.7 on 2025-02-05 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0051_alter_extrapayment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyassistance',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 11, 15, 13, 44, 502054, tzinfo=datetime.timezone.utc), verbose_name='Fecha de fin'),
        ),
    ]
