# Generated by Django 4.2.7 on 2025-02-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0052_alter_weeklyassistance_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyassistance',
            name='end_date',
            field=models.DateField(verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='weeklyassistance',
            name='start_date',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='weeklyassistance',
            name='week_number',
            field=models.IntegerField(verbose_name='Número de semana'),
        ),
    ]
