# Generated by Django 4.2.7 on 2025-07-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistance", "0056_alter_assistance_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extrapayment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Monto del extra (sieempre positivo +)",
                max_digits=10,
                verbose_name="Monto",
            ),
        ),
    ]
