# Generated by Django 4.2.7 on 2025-02-03 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0020_alter_employee_card_number_alter_employee_curp_and_more'),
        ('services', '0011_schedule_hours_schedule_weekly_attendances'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skip_payment', models.BooleanField(default=False, verbose_name='Omitir pago')),
                ('work_days', models.IntegerField(verbose_name='Días trabajados')),
                ('no_attendance_days', models.IntegerField(verbose_name='Días no laborados')),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sub total')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Empleado')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Servicio')),
            ],
        ),
    ]
