# Generated by Django 4.2.7 on 2025-02-03 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0046_alter_weeklyassistance_end_date'),
        ('accounting', '0002_alter_payroll_sub_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='service',
        ),
        migrations.AddField(
            model_name='payroll',
            name='weekly_assistance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assistance.weeklyassistance', verbose_name='Asistencia semanal'),
            preserve_default=False,
        ),
    ]
