# Generated by Django 4.2.7 on 2025-02-04 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_remove_payroll_service_payroll_weekly_assistance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payroll',
            options={'verbose_name': 'Nómina', 'verbose_name_plural': 'Nóminas'},
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='employee',
        ),
    ]
