# Generated by Django 4.2.7 on 2025-02-04 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_payroll_options_remove_payroll_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='no_attendance_days',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='work_days',
        ),
        migrations.AddField(
            model_name='payroll',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de actualización'),
        ),
    ]
