# Generated by Django 4.2.7 on 2025-02-07 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_payroll_discount_loans'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Resumen de nómina',
                'verbose_name_plural': 'Resúmenes de nómina',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounting.payroll',),
        ),
    ]
