# Generated by Django 4.2.7 on 2025-02-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_payrollsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Pagado'),
        ),
    ]
